/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    BetterAuthSecret: {
      type: 'sst.sst.Secret';
      value: string;
    };
    BlobReadWriteToken: {
      type: 'sst.sst.Secret';
      value: string;
    };
    DatabaseUrl: {
      type: 'sst.sst.Secret';
      value: string;
    };
    ElectricSourceId: {
      type: 'sst.sst.Secret';
      value: string;
    };
    ElectricSourceSecret: {
      type: 'sst.sst.Secret';
      value: string;
    };
    InngestEventKey: {
      type: 'sst.sst.Secret';
      value: string;
    };
    InngestSigningKey: {
      type: 'sst.sst.Secret';
      value: string;
    };
    ResendApiKey: {
      type: 'sst.sst.Secret';
      value: string;
    };
    VercelBlobBaseUrl: {
      type: 'sst.sst.Secret';
      value: string;
    };
    VercelBlobStoreId: {
      type: 'sst.sst.Secret';
      value: string;
    };
    Vpc: {
      type: 'sst.aws.Vpc';
    };
    Web: {
      service: string;
      type: 'sst.aws.Service';
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
